services:
  - type: web
    name: cv-midterm-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
      pip install -r requirements.txt
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 5000